name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          
        run: |
          # Get DVC 1.0 
          #pip install dvc[s3]
          
          
          pip install -r requirements.txt
          
          # Pull dataset with DVC 
          dvc pull 
          
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro 
          
          # Use DVC metrics diff to compare metrics to master
          git fetch --prune --unshallow
          dvc metrics diff --show-md master >> report.md
          
          # Add figure to report
          dvc plots diff --target loss.csv --show-vega master > vega.json
          vl2png vega.json -s 1.5 | cml-publish --md  >> report.md
          cml-send-comment report.md 
